[build]
  # All settings blank = use defaults
  publish = "."

[functions]
  directory = "functions"

# Keep your headers, redirects, and environment variables
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  STRIPE_SECRET_KEY = "@stripe_secret_key"
  OPENAI_API_KEY = "@openai_api_key"
