[build]
  publish = "."
  command = ""  # No build command needed for static site

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["jsonwebtoken", "validator"]
  included_files = [
    "netlify/functions/**/*.js",
    "netlify/functions/**/*.json"
  ]

# Function-specific timeouts
[functions."generate-course"]
  timeout = 60

[functions."create-payment-intent"]
  timeout = 30

[functions."stripe-webhook"]
  timeout = 10

# Environment variables for production
[context.production.environment]
  FIREBASE_API_KEY = "@firebase_api_key"
  FIREBASE_AUTH_DOMAIN = "@firebase_auth_domain"
  FIREBASE_PROJECT_ID = "@firebase_project_id"
  FIREBASE_STORAGE_BUCKET = "@firebase_storage_bucket"
  FIREBASE_MESSAGING_SENDER_ID = "@firebase_messaging_sender_id"
  FIREBASE_APP_ID = "@firebase_app_id"
  STRIPE_PUBLISHABLE_KEY = "@stripe_publishable_key"
  OPENAI_API_KEY = "@openai_api_key"

# For preview deployments
[context.deploy-preview.environment]
  NODE_ENV = "staging"
  STRIPE_PUBLISHABLE_KEY = "@stripe_test_publishable_key"

[context.branch-deploy.environment]
  NODE_ENV = "staging"
  STRIPE_PUBLISHABLE_KEY = "@stripe_test_publishable_key"

# Your existing headers and redirects would go here too
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
